services:
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /root/docker/prowlarr/config:/config
      - ./custom:/config/Definitions/Custom
    ports:
      - 9696:9696
    restart: unless-stopped