services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /root/docker/radarr/config:/config
      - /data/media/movies:/movies
      - /data/torrents:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped
