services:
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /root/docker/bazarr/config:/config
      - /root/docker/bazarr/custom-cont-init.d:/custom-cont-init.d:ro
      - /data/media:/media
      - /data/media/tv:/tv
      - /data/media/movies:/movies
    ports:
      - "6767:6767"
    restart: unless-stopped

networks:
  default:
    name: arrsuite
    external: true